name: Python CI with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job for building the Docker image
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t my-python-app .

  # Job for running tests inside the Docker container
  test:
    runs-on: ubuntu-latest
    needs: build  # This job will only run after the "build" job finishes successfully
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests with pytest inside Docker container
        run: |
          docker run my-python-app
